### PR TITLE
Homework submission for Jim Roberts

### PR DESCRIPTION
**Pull request by jroberts-iii**
Run the /Utilities/CreateDatabase project to initialize the database.  The database has a bunch of T-SQL stored procedures that you need.

This has a single MVC page (/Home/Index).  The client gets all of it's data from Web Api controllers.  So we should be able to create a mobile app using the exiting Api.

The feed data is stored in the database and shared between all users.  The users can add their own metadata to the feeds (like which items they have read).

The database throttles feed refreshes.  Right now the feeds will become stale after one minute.

There are several incompatible versions of RSS plus Atom.  So there might be some parser problems.  I tried it with Reddit and Cnn feeds.

This has barely been tested.  There are some unit test for the most basic cases.  DotCover says it is 69% covered.  But there are a lot of interactions cases that need to be added.  

There is no way to determine when the feed items are published.  There is an optional [pubDate], but it is unclear whether [pubDate] is the original publication date, or a bumped publication date.  I saw cases where bumped items had the original publication date.  (So a old item with an old date is at the top of the feed.)

I added a sequence number to all the items to keep them in feed order.  This seems to work pretty well for single feeds.  They always stay pretty much in feed order, even as items age off the feeds.  However, it is not as useful when trying to merge feeds together in some sort of coherent order.  (Think displaying all items from all feeds.)

If you have any questions, please let me know.

With Best Regards,
Jim Roberts

### CODE REVIEW

**Comment by jroberts-iii** [comment]
I refactored the client and pushed it.  I didn't realize that pushes after a pull request get tacked onto the pull request.

Sorry, I hope that doesn't mess things up.

**Comment by jeremyabbott** [comment]
Good morning Jim. it looks like at least one file was included in the project, but not in git. Specifically the file "..\Script\model\api\authenticationApi.d.ts". Can you update the source and commit again?

**Comment by jroberts-iii** [comment]
I pushed it, but it had other changes too.

The last commit I submitted before the pull request was:
Changed server to only get stale rss feeds. Changed search to search …

That commit works and has all the files.

After I make the pull request, I kept messing with the project (I am still messing with it).  I was having a good time and pushed up some more changes not realizing that it was going to affect the pull request.

The stuff I just pushed has a refresh feature that just gets anything new from the server.

**Comment by jroberts-iii** [comment]
BTW, if you already installed the database (ran CreateDatabase project), you will need to reinstall it.  The refresh feature changed a store procedure.

**Comment by jeremyabbott** [comment]
Hi Jim. I'm sorry to bother you again. There is a TypeScript issue that is preventing the solution from building. The error I'm getting is: "Cannot compile external modules unless the '--module' flag is provided.

**Comment by jroberts-iii** [comment]
I have never seen that error before.

Are you using VS 2013?  TypeScript is preinstalled on that version.
Call me:
512.733.2941

Jim

**Comment by jeremyabbott** [comment]
I opened it in 2013 and it built fine. I've been seeing some weird behavior in 2013 that I haven't had an opportunity to address.

New issue: I cannot create the database. I'm consistently getting an error indicating that the database already exists.

**Comment by jroberts-iii** [comment]
I guess you already have a localdb database called FeedReeder.

Let's just change the DB name to something else.  You can change the database by changing these two files:
/Utilities/CreateDatabase/App.config
/Web/FeedReader/Web.config

Look for the appSettings persistence key:
[appSettings]
  [add key="persistence"... /]
[/appSettings]

You will need to change the database name "FeedReader" in two place in each key.  Once in AttachDbFilename, and once in Catalog.

I guess just make it "FeedReaderJim"

You only need to run CreateDatabase one time.  After that you should be able to start the website.

**Comment by jroberts-iii** [comment]
Maybe this will help.  I changed CreateDatabase to prompt you if you want to overwrite the existing database.

**Comment by jroberts-iii** [comment]
Did you get it to work?

I hosted it here if you want to see it:
http://ibcsoftware.com/

**Comment by jeremyabbott** [comment]
Good evening Jim. I was (am) out of the office today, but Ryan and I will get this squared away first thing Monday morning.

**Pull request closed without merging**
